apiVersion: v1
kind: PersistentVolume
metadata:
  name: testing-pv
spec:
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  accessModes: 
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testing-pvc
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: testing-pod
spec:
  containers:
  - name: testing
    image: nginx
    volumeMounts:
    - name: testing
      mountPath: /mnt/data
  volumes:
    - name: testing
      persistentVolumeClaim:
        claimName: testing-pvc