resources:
  - ../../base
namePrefix: dev-

labels:
  - pairs:
      app: dev

patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: myapp
      spec:
        replicas: 1
  - patch: |
      apiVersion: autoscaling/v1
      kind: HorizontalPodAutoscaler
      metadata:
        name: myapp
      spec:
        maxReplicas: 6
        minReplicas: 2
        scaleTargetRef:
          apiVersion: apps/v1
          kind: Deployment
          name: myapp
        targetCPUUtilizationPercentage: 50
      status:
        currentReplicas: 0
        desiredReplicas: 0

# patches:
#   - path: patch-hpa-myapp.yaml
#   - path: patch-hpa-payment.yaml
#   - path: patch-deploy-backend.yaml