resources:
  - ../../base

namePrefix: staging-

commonLabels:
  environment: staging

patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: myapp
      spec:
        replicas: 3
